"""Initial relational schema and durable ledgers."""
from alembic import op
import sqlalchemy as sa
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('body_sha256', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_requests',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('asked_at', sa.Double(), nullable=False),
    sa.Column('expires_at', sa.Double(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_feedback_requests_customer_id'), 'feedback_requests', ['customer_id'], unique=False)
    op.create_table('import_markers',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox',
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('destination', 'id')
    )
    op.create_table('send_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('agent_email', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_intents_message_id'), 'send_intents', ['message_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.Double(), nullable=False),
    sa.Column('closed_at', sa.Double(), nullable=True),
    sa.Column('first_response_at', sa.Double(), nullable=True),
    sa.Column('first_response_agent_id', sa.String(), nullable=True),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('resolution_agent_id', sa.String(), nullable=True),
    sa.Column('reassignments', sa.Integer(), nullable=False),
    sa.Column('frt_seconds', sa.Double(), nullable=True),
    sa.Column('resolution_seconds', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['first_response_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['resolution_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_assigned_agent_id'), 'conversations', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_started_at'), 'conversations', ['started_at'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('at', sa.Double(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('previous_agent_id', sa.String(), nullable=True),
    sa.Column('is_reassignment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['previous_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_conversation_id'), 'assignments', ['conversation_id'], unique=False)
    op.create_table('feedback_results',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.Double(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('response_message_id', sa.String(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('at', sa.Double(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('agent_email', sa.String(), nullable=True),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('sender_kind', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_at'), 'messages', ['at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('feedback_results')
    op.drop_index(op.f('ix_assignments_conversation_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_conversations_started_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_send_intents_message_id'), table_name='send_intents')
    op.drop_table('send_intents')
    op.drop_table('outbox')
    op.drop_table('import_markers')
    op.drop_index(op.f('ix_feedback_requests_customer_id'), table_name='feedback_requests')
    op.drop_table('feedback_requests')
    op.drop_table('deliveries')
    op.drop_table('customers')
    op.drop_table('agents')
    # ### end Alembic commands ###
